# Generated by Django 4.2.16 on 2024-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
